### ISSUE TITLE
Output colors on FreeBSD

### ISSUE THREAD

**Issue by dbaio** [eliangcs/http-prompt#23] opened 2016-05-24 16:31 UTC
Hi.

As talked through email, on execution.py if I remove "stdout=output", the output colors works out.
                #env = Environment(stdout=output)
                env = Environment()

Otherwise, is all printed without colors.

Using shells csh and zsh.

![screen shot 2016-05-23 at 16 44 50](https://cloud.githubusercontent.com/assets/2529335/15511744/3eb3405c-21b3-11e6-9cdc-f71e2672e413.png)

![screen shot 2016-05-23 at 16 45 09](https://cloud.githubusercontent.com/assets/2529335/15511746/433e907c-21b3-11e6-9ca1-a21b41cef6a9.png)

Thanks and congrats for this tool.

**Comment by eliangcs** [comment] 2016-06-03 03:28
@jkbrzt do you know why this happens?

This is how I call `httpie.core.main`: https://github.com/eliangcs/http-prompt/blob/master/http_prompt/execution.py#L282

The reason why I replace stdout with a `BytesIO` is because I need to use `click.echo_via_pager()` to paginate output.

**Comment by eliangcs** [comment] 2016-06-04 05:20
@dbaio After some testing, I think the problem is with the pager you use. Your default pager is probably `more` as opposed to `less`. And `more` doesn't support colors.  Try setting your `PAGER` environment variable to `less` and try again:

On zsh:

```
$ export PAGER=less
```

Or on csh:

```
$ setenv PAGER less
```

**Comment by dbaio** [comment] 2016-06-06 12:19
Hi @eliangcs.
You are right. After doing what you suggested, it worked well.
Thanks again.

**Comment by eliangcs** [comment] 2016-06-06 13:45
Glad to help. Closing.

**Closed by eliangcs** 2016-06-06 13:45 UTC
Labels: help wanted
